export const artifacts: Artifact[] = [
  {
    id: "1",
    creator: "0x1234",
    image_url: "/vercel.svg",
    artifact_hash: "1234",
    license: "open",
    whitelist: [],
    blacklist: [],
  },
  {
    id: "2",
    creator: "0x1234",
    image_url: "/vercel.svg",
    artifact_hash: "1234",
    license: "open",
    whitelist: [],
    blacklist: [],
  },
  {
    id: "3",
    creator: "0x1234",
    image_url: "/vercel.svg",
    artifact_hash: "1234",
    license: "open",
    whitelist: [],
    blacklist: [],
  },
  {
    id: "4",
    creator: "0x1234",
    image_url: "/vercel.svg",
    artifact_hash: "1234",
    license: "open",
    whitelist: [],
    blacklist: [],
  },
  {
    id: "5",
    creator: "0x1234",
    image_url: "/vercel.svg",
    artifact_hash: "1234",
    license: "open",
    whitelist: [],
    blacklist: [],
  },
  {
    id: "6",
    creator: "0x1234",
    image_url: "/vercel.svg",
    artifact_hash: "1234",
    license: "open",
    whitelist: [],
    blacklist: [],
  },
  {
    id: "7",
    creator: "0x1234",
    image_url: "/vercel.svg",
    artifact_hash: "1234",
    license: "open",
    whitelist: [],
    blacklist: [],
  },
  {
    id: "8",
    creator: "0x1234",
    image_url: "/vercel.svg",
    artifact_hash: "1234",
    license: "open",
    whitelist: [],
    blacklist: [],
  },
  {
    id: "9",
    creator: "0x1234",
    image_url: "/vercel.svg",
    artifact_hash: "1234",
    license: "open",
    whitelist: [],
    blacklist: [],
  },
  {
    id: "10",
    creator: "0x1234",
    image_url: "/vercel.svg",
    artifact_hash: "1234",
    license: "open",
    whitelist: [],
    blacklist: [],
  },
];
